[package]
name = "ditto"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "0.8"
wasm-bindgen = "0.2"
minifb = { version = "0.24", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[features]
default = []