name: CI for Ditto CHIP-8 Emulator

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install dependencies for populate.sh
        run: sudo apt-get update && sudo apt-get install -y curl unzip

      - name: Populate ROMs if needed
        run: |
          chmod +x ./populate.sh
          ./populate.sh

      - name: Build the project (release)
        run: cargo build --release

      - name: Run tests
        run: cargo test --all --release

      - name: Upload test results (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            target/debug/deps/*.log
            target/debug/deps/*.d
            target/debug/deps/*.stderr
            target/debug/deps/*.stdout